mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.18.129:3306/e3mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
# redis-single
#    host: 192.168.18.129
#    port: 6379
# redis-cluster
    cluster:
      nodes: 192.168.18.129:6380,192.168.18.129:6381,192.168.18.129:6382

dubbo:
  application:
    name: e3-content
  registry:
    address: zookeeper://192.168.18.129:2181
  scan:
    basePackages: guo.ping.e3mall.content.service
  protocol:
    port: 20881